// console.table(elements);
// console.log(getElement(elements,"He"));
// console.log(splitEquationToFormulas("CH4 + O2"));
// console.log(getCoefficient("4CH3"));
// console.log(getCoefficient("CH3"));
// console.log(partitionCoefficient("2CH3"));
// console.log(partitionCoefficient("CH3"));
// console.log(tallyElements("2CH3"), " coeff");
// console.log(tallyElements("5C4Hh3Uuu3"));
// console.log(tallyElements("H2O"));
checkChemicalBalance("Na + Cl", "NaCl");
checkChemicalBalance("2CH4 + CO2", "CO2 + H2O");
